import { useState, type ReactNode } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Database, Trash2 } from "lucide-react";

import {
  clearAllData,
  getSettings,
  removeSampleData,
  seedSampleData,
  setSandbox,
} from "../../lib/api";
import { ViewShell } from "./ViewShell";

// One Data Management card: a Sandbox toggle plus seed / remove-samples / clear-all. Destructive
// actions use an inline two-step confirm (no modal dependency); Clear all is the only red control.
export function SettingsView() {
  const qc = useQueryClient();
  const settings = useQuery({ queryKey: ["settings"], queryFn: getSettings });

  const invalidateData = () => {
    void qc.invalidateQueries({ queryKey: ["datasets"] });
    void qc.invalidateQueries({ queryKey: ["runs"] });
    void qc.invalidateQueries({ queryKey: ["selection"] });
  };

  const sandbox = useMutation({
    mutationFn: (enabled: boolean) => setSandbox(enabled),
    onSuccess: (s) => {
      qc.setQueryData(["settings"], s);
      void qc.invalidateQueries({ queryKey: ["selection"] });
    },
  });
  const seed = useMutation({ mutationFn: seedSampleData, onSuccess: invalidateData });
  const removeSamples = useMutation({ mutationFn: removeSampleData, onSuccess: invalidateData });
  const clearAll = useMutation({ mutationFn: clearAllData, onSuccess: invalidateData });

  const on = settings.data?.sandbox_enabled ?? false;

  return (
    <ViewShell
      title="Settings"
      subtitle="Manage your local data and the simulated sandbox. Everything here stays on this machine."
    >
      <section className="grid max-w-2xl gap-6 rounded-xl border border-(--color-panel-line) bg-(--color-panel-card) p-6">
        <div>
          <h3 className="text-sm font-medium text-(--color-ink)">Data management</h3>
          <p className="mt-1 text-sm text-(--color-ink-muted)">
            Reset or populate this install. Sample data is generated by the simulated mocks and is
            clearly flagged.
          </p>
        </div>

        {/* Sandbox toggle */}
        <div className="flex items-start justify-between gap-4 border-t border-(--color-panel-line) pt-4">
          <div>
            <p className="text-sm text-(--color-ink)">Sandbox</p>
            <p className="text-xs text-(--color-ink-faint)">
              Show simulated Mock models in the picker for keyless trial runs. Off by default — mock
              runs are not a real evaluation.
            </p>
          </div>
          <button
            type="button"
            role="switch"
            aria-checked={on}
            aria-label="Sandbox"
            disabled={settings.isLoading || sandbox.isPending}
            onClick={() => sandbox.mutate(!on)}
            className={
              "relative h-6 w-11 shrink-0 rounded-full transition-colors " +
              (on ? "bg-(--color-accent)" : "bg-(--color-panel-line-strong)")
            }
          >
            <span
              className={
                "absolute top-0.5 h-5 w-5 rounded-full bg-white transition-all " +
                (on ? "left-[1.375rem]" : "left-0.5")
              }
            />
          </button>
        </div>

        {/* Seed */}
        <ActionRow
          label="Seed sample data"
          description="Add a sample dataset and a finished Proof Receipt so the product isn't empty. Re-running replaces the previous sample."
          actionLabel="Seed sample data"
          icon={<Database aria-hidden className="h-4 w-4" />}
          pending={seed.isPending}
          onConfirm={() => seed.mutate()}
          done={
            seed.isSuccess
              ? `Seeded ${seed.data?.datasets} dataset, ${seed.data?.receipts} receipt.`
              : null
          }
        />

        {/* Remove samples */}
        <ActionRow
          label="Remove sample data"
          description="Delete only the seeded sample dataset and receipts. Your own datasets and receipts are kept."
          actionLabel="Remove sample data"
          pending={removeSamples.isPending}
          onConfirm={() => removeSamples.mutate()}
          done={removeSamples.isSuccess ? "Sample data removed." : null}
        />

        {/* Clear all — destructive */}
        <ActionRow
          label="Clear all data"
          description="Permanently delete ALL datasets and receipts on this install (samples and your own). Settings are kept. This cannot be undone."
          actionLabel="Clear all data"
          confirmLabel="Confirm clear"
          destructive
          icon={<Trash2 aria-hidden className="h-4 w-4" />}
          pending={clearAll.isPending}
          onConfirm={() => clearAll.mutate()}
          done={clearAll.isSuccess ? "All data cleared." : null}
        />
      </section>
    </ViewShell>
  );
}

// An action with an inline two-step confirm: first click reveals Confirm/Cancel; only Confirm fires.
function ActionRow({
  label,
  description,
  actionLabel,
  confirmLabel = "Confirm",
  destructive = false,
  icon,
  pending,
  onConfirm,
  done,
}: {
  label: string;
  description: string;
  actionLabel: string;
  confirmLabel?: string;
  destructive?: boolean;
  icon?: ReactNode;
  pending: boolean;
  onConfirm: () => void;
  done: string | null;
}) {
  const [armed, setArmed] = useState(false);
  const base =
    "inline-flex items-center gap-1.5 rounded-lg border px-3 py-2 text-sm transition-colors disabled:opacity-50";
  return (
    <div className="grid gap-2 border-t border-(--color-panel-line) pt-4">
      <p className="text-sm text-(--color-ink)">{label}</p>
      <p className="text-xs text-(--color-ink-faint)">{description}</p>
      <div className="flex items-center gap-2">
        {!armed ? (
          <button
            type="button"
            aria-label={actionLabel}
            disabled={pending}
            onClick={() => setArmed(true)}
            className={
              base +
              " " +
              (destructive
                ? "border-(--color-danger)/50 text-(--color-danger) hover:bg-(--color-danger)/10"
                : "border-(--color-panel-line) text-(--color-ink) hover:border-(--color-panel-line-strong)")
            }
          >
            {icon}
            {actionLabel}
          </button>
        ) : (
          <>
            <button
              type="button"
              aria-label={confirmLabel}
              disabled={pending}
              onClick={() => {
                onConfirm();
                setArmed(false);
              }}
              className={
                base +
                " " +
                (destructive
                  ? "border-(--color-danger) bg-(--color-danger)/10 text-(--color-danger)"
                  : "border-(--color-accent) bg-(--color-accent)/10 text-(--color-ink)")
              }
            >
              {confirmLabel}
            </button>
            <button
              type="button"
              onClick={() => setArmed(false)}
              className={base + " border-(--color-panel-line) text-(--color-ink-muted)"}
            >
              Cancel
            </button>
          </>
        )}
        {done ? <span className="text-xs text-(--color-ink-faint)">{done}</span> : null}
      </div>
    </div>
  );
}
