"""Seed realistic sample data so a new install isn't empty: one sample dataset plus a
finished Proof Receipt over it, generated by the keyless mocks (deterministic, no network).
Idempotent — re-seeding clears prior samples first."""

from __future__ import annotations

import sqlite3

from orionfold.data import load_dataset
from orionfold.domain.models import Candidate, Dataset, ProofBrief
from orionfold.proof.engine import run_proof
from orionfold.scoring.rubric import default_rubric_for
from orionfold.storage import repository

SAMPLE_DATASET_ID = "sample-investment-memo"
SAMPLE_RUN_ID = "run_sample01"
SAMPLE_CREATED_AT = "2026-06-19T12:00:00Z"
SAMPLE_BRIEF = ProofBrief(
    task_name="Sample · investment memo summarization",
    decision_question="Which model should I trust for client memos?",
    success_criteria="At least 80% similarity to the analyst summary.",
)


def _sample_dataset() -> Dataset:
    base = load_dataset("investment-memo-summarization")
    return base.model_copy(
        update={"id": SAMPLE_DATASET_ID, "name": "Sample · investment memo summarization"}
    )


def seed_sample_data(conn: sqlite3.Connection) -> tuple[int, int]:
    """(Re)create the sample dataset + receipt. Returns (datasets, receipts) created."""
    repository.remove_sample_data(conn)  # idempotent: clear prior samples first
    dataset = _sample_dataset()
    repository.insert_sample_dataset(conn, dataset)
    report = run_proof(
        run_id=SAMPLE_RUN_ID,
        created_at=SAMPLE_CREATED_AT,
        brief=SAMPLE_BRIEF,
        dataset=dataset,
        candidates=[
            Candidate(id="mock_good", label="Mock · good", provider_id="mock_good"),
            Candidate(id="mock_bad", label="Mock · bad", provider_id="mock_bad"),
        ],
        rubric=default_rubric_for(dataset),
    )
    repository.save_report(conn, report, is_sample=True)
    return (1, 1)
