"""Seed realistic sample data so a new install isn't empty: a small set of sample datasets,
each with a finished Proof Receipt generated by the keyless mocks (deterministic, no network).
Idempotent — re-seeding clears prior samples first.

The bundled samples span four rubric classes so a fresh install reads like a real builder's
tasks: keypoint (investment memo), exact (ticket triage), contains (contract extraction), and
the similarity/LLM-judge path (buyer-need match). Each spec carries the display metadata a
user-imported dataset gets (created_at / source / check_hint) plus its own receipt run id."""

from __future__ import annotations

import sqlite3
from dataclasses import dataclass

from orionfold.data import load_dataset
from orionfold.domain.models import Candidate, Dataset, ProofBrief
from orionfold.proof.engine import run_proof
from orionfold.scoring.rubric import default_rubric_for
from orionfold.storage import repository

SAMPLE_SOURCE = "Bundled with Orionfold"
SAMPLE_CREATED_AT = "2026-06-19T12:00:00Z"

# Back-compat alias for the original investment-memo sample (referenced by tests + tooling).
SAMPLE_DATASET_ID = "sample-investment-memo"
SAMPLE_RUN_ID = "run_sample01"
SAMPLE_CHECK_HINT = "eyeball"
SAMPLE_BRIEF = ProofBrief(
    task_name="Sample · investment memo summarization",
    decision_question="Which model should I trust for client memos?",
    success_criteria="At least 80% similarity to the analyst summary.",
)


@dataclass(frozen=True)
class SampleSpec:
    """One bundled sample: a catalog dataset re-skinned as a sample + a seeded receipt.

    ``check_hint`` is display metadata AND drives the seeded receipt's scoring kind via
    ``default_rubric_for`` (exact/numeric → exact, substring → contains, eyeball/"" →
    keypoint-or-similarity). Display-only on the row; never on the domain Dataset, so
    config_hash is untouched.
    """

    catalog_id: str
    sample_id: str
    name: str
    run_id: str
    brief: ProofBrief
    check_hint: str


_SAMPLES: list[SampleSpec] = [
    SampleSpec(
        catalog_id="investment-memo-summarization",
        sample_id=SAMPLE_DATASET_ID,
        name="Sample · investment memo summarization",
        run_id=SAMPLE_RUN_ID,
        brief=SAMPLE_BRIEF,
        # The summaries are paraphrased free-form, graded by judgment (the demo defaults to the
        # LLM judge), so "eyeball" is the honest hint — display-only; the seed scores by keypoint.
        check_hint=SAMPLE_CHECK_HINT,
    ),
    SampleSpec(
        catalog_id="support-ticket-triage",
        sample_id="sample-ticket-triage",
        name="Sample · support ticket triage",
        run_id="run_sample02",
        brief=ProofBrief(
            task_name="Sample · support ticket triage",
            decision_question="Which model routes tickets to the right queue?",
            success_criteria="The exact category label, every time.",
        ),
        check_hint="exact",
    ),
    SampleSpec(
        catalog_id="contract-field-extraction",
        sample_id="sample-contract-extraction",
        name="Sample · contract field extraction",
        run_id="run_sample03",
        brief=ProofBrief(
            task_name="Sample · contract field extraction",
            decision_question="Which model pulls the right field from a clause?",
            success_criteria="The correct value appears in the answer.",
        ),
        check_hint="substring",
    ),
    SampleSpec(
        catalog_id="buyer-need-solution-match",
        sample_id="sample-buyer-match",
        name="Sample · buyer need to solution match",
        run_id="run_sample04",
        brief=ProofBrief(
            task_name="Sample · buyer need to solution match",
            decision_question="Which model writes the sharpest, best-grounded pitch?",
            success_criteria="A specific pitch with a credible named proof point.",
        ),
        # No hint → similarity backend; the UI demo-judge-default auto-picks the LLM judge
        # because this dataset is is_sample with no resolved keypoints.
        check_hint="",
    ),
]


def _sample_dataset(spec: SampleSpec) -> Dataset:
    base = load_dataset(spec.catalog_id)
    return base.model_copy(update={"id": spec.sample_id, "name": spec.name})


def _seed_one(conn: sqlite3.Connection, spec: SampleSpec) -> None:
    dataset = _sample_dataset(spec)
    repository.insert_sample_dataset(
        conn,
        dataset,
        created_at=SAMPLE_CREATED_AT,
        source=SAMPLE_SOURCE,
        check_hint=spec.check_hint,
    )
    report = run_proof(
        run_id=spec.run_id,
        created_at=SAMPLE_CREATED_AT,
        brief=spec.brief,
        dataset=dataset,
        candidates=[
            Candidate(id="mock_good", label="Mock · good", provider_id="mock_good"),
            Candidate(id="mock_bad", label="Mock · bad", provider_id="mock_bad"),
        ],
        # The seed scores keylessly with the mocks; the hint drives the kind (exact/contains)
        # so the seeded receipt matches how a real run on this dataset would be scored.
        rubric=default_rubric_for(dataset, check_hint=spec.check_hint),
    )
    repository.save_report(conn, report, is_sample=True)


def seed_sample_data(conn: sqlite3.Connection) -> tuple[int, int]:
    """(Re)create the sample datasets + receipts. Returns (datasets, receipts) created."""
    repository.remove_sample_data(conn)  # idempotent: clear prior samples first
    for spec in _SAMPLES:
        _seed_one(conn, spec)
    return (len(_SAMPLES), len(_SAMPLES))
